#!/usr/bin/env python3
"""Turn users.plain.txt (real addresses) into users.txt (SHA-256 hashes).

users.plain.txt is the human-readable list and stays out of git, so the family's
addresses are never published. users.txt is what the app fetches and what gets
deployed. Run this after editing users.plain.txt:

    python hash-users.py

The normalisation here (strip, lowercase) must match isAllowed() in index.html,
or a valid account will be rejected.
"""

import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).parent
SOURCE = HERE / "users.plain.txt"
TARGET = HERE / "users.txt"


def entries(text):
    for chunk in text.replace(",", "\n").splitlines():
        line = chunk.strip().lower()
        if line and not line.startswith("#"):
            yield line


def main():
    if not SOURCE.exists():
        sys.exit(f"{SOURCE.name} not found — create it with one email address per line.")

    addresses = list(entries(SOURCE.read_text(encoding="utf-8")))
    if not addresses:
        sys.exit(f"{SOURCE.name} has no addresses in it.")

    already_hashed = [a for a in addresses if len(a) == 64 and all(c in "0123456789abcdef" for c in a)]
    if already_hashed:
        sys.exit(f"{SOURCE.name} looks like it already holds hashes — it should hold real addresses.")

    lines = [
        "# SHA-256 hashes of the allowed Google accounts. Generated by hash-users.py.",
        "# Edit users.plain.txt and re-run that script; do not hand-edit this file.",
    ]
    lines += [hashlib.sha256(a.encode("utf-8")).hexdigest() for a in sorted(set(addresses))]

    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {TARGET.name}: {len(set(addresses))} account(s) hashed")


if __name__ == "__main__":
    main()
